/**
 * @file ErrorCodes.js
 * Frozen enumeration of all standardized application error codes.
 */

export const ErrorCodes = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  PASSWORD_CHANGE_REQUIRED: "PASSWORD_CHANGE_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  DUPLICATE_LOGIN_ID: "DUPLICATE_LOGIN_ID",
  ALREADY_CHECKED_IN: "ALREADY_CHECKED_IN",
  NOT_CHECKED_IN: "NOT_CHECKED_IN",
  INSUFFICIENT_LEAVE_BALANCE: "INSUFFICIENT_LEAVE_BALANCE",
  OVERLAPPING_LEAVE: "OVERLAPPING_LEAVE",
  ALREADY_REVIEWED: "ALREADY_REVIEWED",
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE"
});
